language: objective-c
xcode_project: AsmHelper.xcodeproj
xcode_scheme: AsmHelper
osx_image: xcode8.3

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

script:
    - xcodebuild clean build -workspace Workspace.xcworkspace -scheme SMTor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
